### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by nicklasb** [pycontribs/activedirectory#6]
Hi,
I am wondering of the status of the project. 
There is currently no documentation, and there have been no commits for a long while...so please take no offence.

Edit: If it is in a proper working state outside the lack of commits, yes I am prepared to help out to improve the situation.
##

**Comment by FlipperPA** [comment]
I've actually had a lot of luck using standard LDAP libraries to connect to Active Directory with straight Python. I've been keeping an eye on this project, but in the meantime, I've been using:

git+https://github.com/rbarrois/python-ldap.git@py3

and more recently, also with django-python3-ldap:

https://github.com/cannatag/ldap3

**Comment by ssbarnea** [comment]
I am not using the library anymore as I changed jobs and we don't use LDAP here. Still, if someone is interested in contributing and maintaining the project I am more then willing to add them full access.

**Comment by nicklasb** [comment]
@FlipperPA: 
Thanks for your reply, for some reason I haven't seen that until now.
@ssbarnea :
Ok, not now, but I will get back if this becomes relevant again.
